### PR TITLE
Allow feature, abundance refactoring

### PR DESCRIPTION
**Pull request by pimotte**
This PR propagates the changes from abundance service, and introduces allow-support (private channels)

- [x] Modify waardepapieren-service 
- [x] Modify clerk-frontend
- [x] Fix intermittend test failure due to error bubbling at the end (waardepapieren-service)

### CODE REVIEW

**Comment by pimotte** [comment]
Current status:

Modifications on wp-service seem functional, but there is a consistency issue with the test

**Comment by pimotte** [comment]
Consistency issue in wp-service has been fixed with a slightly ugly patch. I've put in a PR for core which would enable the correct fix: https://github.com/discipl/core/pull/43

I would be okay with merging this now and propagating that fix later, I've put a TODO marker there for when this is relevant.

**Comment by bkaptijn** [comment]
travis build failed. Also discipl/core#43 has been merged, maybe apply this too now before merge?

**Comment by bkaptijn** [comment]
Ok will merge this now

**Pull request merged**
