### PR TITLE
Configurability and smaller QR code

### PR DESCRIPTION
**Pull request by pimotte**
I took the liberty of removing the download-button functionality, since it broke the UI for me, I propose we separate this out to a future PR.

I also introduced a fairly nasty hack to obtain the link of an observed claim. There's two ways we could resolve this:
1. Refactor the discipl-paper-wallet issue method to not require the link of the attestation. (https://github.com/discipl/discipl-paper-wallet/pull/7)
2. Add the claim link to the result of observe in ephemeral.

I actually think we should be doing both of these.

### CODE REVIEW

**Comment by bkaptijn** [comment]
Observe should export data more in line with export so including the link. Also , yes i guess paper wallet should not require a link to a claim with a link to the claim to be issued but just issues the claim it got a link for..

**Comment by bkaptijn** [comment]
Irt download button. This worked for me (downloading as .png that is) ..

**Comment by pimotte** [comment]
> Irt download button. This worked for me (downloading as .png that is) ..

I'm aware, but since it did not work on my machine, and integrating it was complex enough as it is, I chose this route. Reverting 33bd74e should be a good starting point to properly re-introduce the feature.

**Comment by pimotte** [comment]
I've released paper-wallet v0.4.0, which removes the need for the ugly hack, so this PR is good to merge (if the build succeeds).

I do have a remark, which is that the configuration is now still bundled with the source files, rather than in the environment. The stuff we do set in the environment is actually not sourced from the configuration files. I don't see this as a problem for now, and it's a big step in the right direction, but if we want to publish a waardepapieren-service docker image that can be used in production, this could be kind of problematic.

**Comment by bkaptijn** [comment]
Ok for now

**Comment by bkaptijn** [comment]
Though configurabillity as a feature is not finished, I'll merge this first part of this work.

**Pull request merged**
